### ISSUE TITLE
Error Rscript install shiny

### ISSUE THREAD

**Issue by ragapack** [dirkschumacher/r-shiny-electron#32]
Hi,
I made a clone and run the instructions from your Quickstart. Using a Win10 PC.
Got this error message.
C:\Users\Thomas\Documents\GitHub\r-shiny-electron>"C:\Program Files\R\R-3.4.1\bin\x64\Rscript.exe" add-cran-binary-pkgs.R
Error in loadNamespace(name) : there is no package called 'automagic'
Calls: setdiff ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Any hint how to solve this?
Thank you
Thomas

**Comment by dirkschumacher** [comment]
Just install the package `automagic`. It is used to detect the dependencies of the shiny app.
