### ISSUE TITLE
How do extra packages get installed?

### ISSUE THREAD

**Issue by md0u80c9** [dirkschumacher/r-shiny-electron#33]
Hi,

Just looking at this with a view to deploying my R shiny dashboard.

Apologies - I couldn't find any documentation beyond the readme - if there are any, please could you signpost me to them?

Looking at add-cran-binary-pkgs.R, this appears to install Shiny and its dependencies.

What do you need to do if your Shiny app has other dependencies?

My install currently already has this:

```
library(shiny)
library(shinyBS)
library(dplyr)
library(purrr)
library(ggplot2)
library(tibbletime)
library(shinydashboard)
library(survival)
library(survminer)
library(ggpubr)
library(chron)

```

Do they need to go within that R script, or somewhere else, or is something reading them from the Shiny app that I just can't see?

**Comment by dirkschumacher** [comment]
Extra packages are installed by downloading the binaries for the specific platform and place them in the library directory of R. You can use `add-cran-binary-pkgs.R` script for that. It runs through your code in `./shiny` and looks for packages.
