### ISSUE TITLE
Default path for loading data?

### ISSUE THREAD

**Issue by md0u80c9** [dirkschumacher/r-shiny-electron#34]
Hi,

Sorry - another newbie question from looking at this deployment.

Until the team have deployed SQL Server for our data source, I'm having to work from a CSV data file which I don't want to include in the binary for our prototyped shiny dashboard.

Does Shiny Electron have a default path? Ie. can I ask the user to deploy the app in the same working directory as the data to avoid having to locate the data file before seeing the dashboard on each load?

**Comment by dirkschumacher** [comment]
You could use `getwd()` and place the data in the `shiny` directorty. Maybe that could work.
