### ISSUE TITLE
Error during npm start

### ISSUE THREAD

**Issue by rickyars** [dirkschumacher/r-shiny-electron#38]
```
> r-shiny-electron@1.0.0 start /Users/rrs/Documents/r-shiny-electron
> electron-forge start

✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies
✔ Launching Application
{ Error: Command failed: /Users/rrs/Documents/r-shiny-electron/r-mac/bin/R --vanilla -f /Users/rrs/Documents/r-shiny-electron/start-shiny.R
Error in rbind(info, getNamespaceInfo(env, "S3methods")) : 
  number of columns of matrices must match (see arg 2)
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

**Comment by gegrimm** [comment]
This is an issue with your shiny application/code, likely something in your `global.R` or startup code if you are using a single-file `app.R` structure. When you `runApp()` in RStudio do you see the same error?

The error appears to be that you attempt to call `rbind()` on two matrices or data.frame objects that have differing numbers of columns.

**Comment by rickyars** [comment]
turns out i didn't have anything in my shiny directory. whoops!
